//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.InterfaceCalculator")]
    public interface InterfaceCalculator
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceCalculator/SetNumbers", ReplyAction="http://tempuri.org/InterfaceCalculator/SetNumbersResponse")]
        void SetNumbers(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceCalculator/SetNumbers", ReplyAction="http://tempuri.org/InterfaceCalculator/SetNumbersResponse")]
        System.Threading.Tasks.Task SetNumbersAsync(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceCalculator/CalculateAddition", ReplyAction="http://tempuri.org/InterfaceCalculator/CalculateAdditionResponse")]
        double CalculateAddition(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceCalculator/CalculateAddition", ReplyAction="http://tempuri.org/InterfaceCalculator/CalculateAdditionResponse")]
        System.Threading.Tasks.Task<double> CalculateAdditionAsync(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceCalculator/CalculateSubtraction", ReplyAction="http://tempuri.org/InterfaceCalculator/CalculateSubtractionResponse")]
        double CalculateSubtraction(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceCalculator/CalculateSubtraction", ReplyAction="http://tempuri.org/InterfaceCalculator/CalculateSubtractionResponse")]
        System.Threading.Tasks.Task<double> CalculateSubtractionAsync(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceCalculator/CalculateMultiplication", ReplyAction="http://tempuri.org/InterfaceCalculator/CalculateMultiplicationResponse")]
        double CalculateMultiplication(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceCalculator/CalculateMultiplication", ReplyAction="http://tempuri.org/InterfaceCalculator/CalculateMultiplicationResponse")]
        System.Threading.Tasks.Task<double> CalculateMultiplicationAsync(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceCalculator/CalculateDivision", ReplyAction="http://tempuri.org/InterfaceCalculator/CalculateDivisionResponse")]
        double CalculateDivision(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceCalculator/CalculateDivision", ReplyAction="http://tempuri.org/InterfaceCalculator/CalculateDivisionResponse")]
        System.Threading.Tasks.Task<double> CalculateDivisionAsync(double number1, double number2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface InterfaceCalculatorChannel : ServiceReference1.InterfaceCalculator, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class InterfaceCalculatorClient : System.ServiceModel.ClientBase<ServiceReference1.InterfaceCalculator>, ServiceReference1.InterfaceCalculator
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public InterfaceCalculatorClient() : 
                base(InterfaceCalculatorClient.GetDefaultBinding(), InterfaceCalculatorClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_InterfaceCalculator.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceCalculatorClient(EndpointConfiguration endpointConfiguration) : 
                base(InterfaceCalculatorClient.GetBindingForEndpoint(endpointConfiguration), InterfaceCalculatorClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceCalculatorClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(InterfaceCalculatorClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceCalculatorClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(InterfaceCalculatorClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void SetNumbers(double number1, double number2)
        {
            base.Channel.SetNumbers(number1, number2);
        }
        
        public System.Threading.Tasks.Task SetNumbersAsync(double number1, double number2)
        {
            return base.Channel.SetNumbersAsync(number1, number2);
        }
        
        public double CalculateAddition(double number1, double number2)
        {
            return base.Channel.CalculateAddition(number1, number2);
        }
        
        public System.Threading.Tasks.Task<double> CalculateAdditionAsync(double number1, double number2)
        {
            return base.Channel.CalculateAdditionAsync(number1, number2);
        }
        
        public double CalculateSubtraction(double number1, double number2)
        {
            return base.Channel.CalculateSubtraction(number1, number2);
        }
        
        public System.Threading.Tasks.Task<double> CalculateSubtractionAsync(double number1, double number2)
        {
            return base.Channel.CalculateSubtractionAsync(number1, number2);
        }
        
        public double CalculateMultiplication(double number1, double number2)
        {
            return base.Channel.CalculateMultiplication(number1, number2);
        }
        
        public System.Threading.Tasks.Task<double> CalculateMultiplicationAsync(double number1, double number2)
        {
            return base.Channel.CalculateMultiplicationAsync(number1, number2);
        }
        
        public double CalculateDivision(double number1, double number2)
        {
            return base.Channel.CalculateDivision(number1, number2);
        }
        
        public System.Threading.Tasks.Task<double> CalculateDivisionAsync(double number1, double number2)
        {
            return base.Channel.CalculateDivisionAsync(number1, number2);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_InterfaceCalculator))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_InterfaceCalculator))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7026/Calculator.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return InterfaceCalculatorClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_InterfaceCalculator);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return InterfaceCalculatorClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_InterfaceCalculator);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_InterfaceCalculator,
        }
    }
}
